import type { AdminAccount, Product, ShippingRates } from "./types";

export const ADMIN_WHATSAPP = "6281221121125";

export const SHIPPING_RATES: ShippingRates = {
  "Bogor Kota": 22000,
  Jabodetabek: 30000,
  Bandung: 24000,
  "Pulau Jawa": 39000,
  "Luar Jawa": 60000,
};

export const ADMIN_ACCOUNTS: AdminAccount[] = [
  { id: "zeemy", name: "ZeeMy", avatarIndex: 2 },
  { id: "silmy", name: "Silmy", avatarIndex: 1 },
  { id: "mina", name: "Mina", avatarIndex: 0 },
];

export const PRODUCTS: Product[] = [
  {
    id: "bear-plush",
    title: "Berry Bear Plush",
    note: "Boneka beruang super lembut, tinggi sekitar 32 cm. Cocok buat hadiah atau teman tidur.",
    price: 129000,
    fee: 25000,
    images: [],
    visual: "🐻",
    category: "Plushie",
    stock: 7,
    sold: 38,
    createdAt: 1786221000000,
    pinned: true,
    soldOut: false,
    availability: "ready",
    order: 0,
  },
  {
    id: "pink-bottle",
    title: "Sakura Tumbler",
    note: "Botol minum 650 ml dengan strap, tutup rapat, dan motif sakura edisi Bandung.",
    price: 89000,
    fee: 20000,
    images: [],
    visual: "🧋",
    category: "Lifestyle",
    stock: 11,
    sold: 64,
    createdAt: 1786134600000,
    pinned: true,
    soldOut: false,
    availability: "ready",
    order: 1,
  },
  {
    id: "ribbon-pouch",
    title: "Ribbon Mini Pouch",
    note: "Pouch mini warna baby pink dengan detail pita. Muat lip product, kartu, dan kunci.",
    price: 79000,
    fee: 18000,
    images: [],
    visual: "🎀",
    category: "Bag",
    stock: 4,
    sold: 29,
    createdAt: 1786048200000,
    pinned: false,
    soldOut: false,
    availability: "preorder",
    order: 2,
  },
  {
    id: "pink-tote",
    title: "Sweet Day Tote Bag",
    note: "Tote bag ringan untuk daily use. Ada kantong kecil di bagian dalam dan penutup magnet.",
    price: 149000,
    fee: 25000,
    images: [],
    visual: "👜",
    category: "Bag",
    stock: 6,
    sold: 22,
    createdAt: 1785961800000,
    pinned: false,
    soldOut: false,
    availability: "po_open",
    order: 3,
  },
  {
    id: "sakura-mirror",
    title: "Sakura Pocket Mirror",
    note: "Cermin lipat dua sisi dengan ilustrasi sakura pixel. Tipis dan mudah dibawa.",
    price: 45000,
    fee: 15000,
    images: [],
    visual: "🌸",
    category: "Beauty",
    stock: 9,
    sold: 71,
    createdAt: 1785875400000,
    pinned: false,
    soldOut: false,
    availability: "ready",
    order: 4,
  },
  {
    id: "strawberry-cake",
    title: "Strawberry Cake Charm",
    note: "Bag charm bentuk cake strawberry. Stok edisi ini sudah habis, tapi tetap dipajang buat referensi.",
    price: 59000,
    fee: 15000,
    images: [],
    visual: "🍰",
    category: "Accessories",
    stock: 0,
    sold: 48,
    createdAt: 1785789000000,
    pinned: false,
    soldOut: true,
    availability: "sold_out",
    order: 5,
  },
];

export const formatRupiah = (value: number) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
